In [1]:
import gym
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt

import time

In [2]:
env = gym.make("MountainCar-v0")

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


In [3]:
env.reset()
# env.render()

for episode in range(20):
    env.reset()
    for i in range(40):
        env.render()
        env.step(2)
    for i in range(40):
        env.render()
        env.step(1)
    for i in range(50): 
        env.render()
        env.step(2)
    for i in range(50):
        env.render()
        env.step(1)
    for i in range(70):
        env.render()
        env.step(2)
    print(env.step(2))
    env.close()

(array([0.6 , 0.07]), -1.0, True, {})


(array([0.6 , 0.07]), -1.0, True, {})


(array([0.6 , 0.07]), -1.0, True, {})


(array([0.6 , 0.07]), -1.0, True, {})


(array([0.6 , 0.07]), -1.0, True, {})


(array([0.6 , 0.07]), -1.0, True, {})


(array([0.6       , 0.06422959]), -1.0, True, {})


(array([0.6 , 0.07]), -1.0, True, {})


(array([0.6 , 0.07]), -1.0, True, {})


(array([0.6 , 0.07]), -1.0, True, {})


(array([0.6 , 0.07]), -1.0, True, {})


(array([0.6 , 0.07]), -1.0, True, {})


(array([0.6 , 0.07]), -1.0, True, {})


(array([0.6 , 0.07]), -1.0, True, {})


(array([0.6 , 0.07]), -1.0, True, {})


(array([0.6 , 0.07]), -1.0, True, {})


(array([0.6 , 0.07]), -1.0, True, {})


(array([0.6 , 0.07]), -1.0, True, {})


(array([0.6 , 0.07]), -1.0, True, {})


(array([0.6 , 0.07]), -1.0, True, {})
