In [1]:
import gym
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt

import time

In [2]:
env = gym.make("MountainCar-v0")

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


In [3]:
env.reset()


for episode in range(5):
    curPos, curVel = env.reset()
    [newPos, newVel],reward, done, _  = env.step(2)

    while not done:
        env.render()
        if newPos > curPos or newPos < -0.9:
            curPos = newPos
            [newPos, newVel],reward, done, _  = env.step(2)
        else:
            curPos = newPos
            [newPos, newVel],reward, done, _  = env.step(1)
        env.close()
    print([newPos, newVel],reward, done, _)

[-0.5940995  0.       ]
(array([-0.59257467,  0.00152482]), -1.0, False, {})
(array([-0.58953622,  0.00303846]), -1.0, False, {})
(array([-0.58500645,  0.00452977]), -1.0, False, {})
(array([-0.57901872,  0.00598773]), -1.0, False, {})
(array([-0.57161726,  0.00740146]), -1.0, False, {})
(array([-0.5628569 ,  0.00876036]), -1.0, False, {})
(array([-0.55280279,  0.01005411]), -1.0, False, {})
(array([-0.54152992,  0.01127286]), -1.0, False, {})
(array([-0.52912264,  0.01240728]), -1.0, False, {})
(array([-0.51567393,  0.01344871]), -1.0, False, {})
(array([-0.50128465,  0.01438928]), -1.0, False, {})
(array([-0.48606261,  0.01522205]), -1.0, False, {})
(array([-0.47012148,  0.01594112]), -1.0, False, {})
(array([-0.45357972,  0.01654176]), -1.0, False, {})
(array([-0.43655925,  0.01702047]), -1.0, False, {})
(array([-0.41918419,  0.01737507]), -1.0, False, {})
(array([-0.40157949,  0.0176047 ]), -1.0, False, {})
(array([-0.38386963,  0.01770986]), -1.0, False, {})
(array([-0.36617732,  

(array([0.6       , 0.03457786]), -1.0, True, {})
(array([0.6       , 0.03514586]), -1.0, True, {})
(array([0.6       , 0.03571387]), -1.0, True, {})
(array([0.6       , 0.03628187]), -1.0, True, {})
(array([0.6       , 0.03684988]), -1.0, True, {})
(array([0.6       , 0.03741788]), -1.0, True, {})
(array([0.6       , 0.03798589]), -1.0, True, {})
(array([0.6       , 0.03855389]), -1.0, True, {})
(array([0.6      , 0.0391219]), -1.0, True, {})
(array([0.6       , 0.03968991]), -1.0, True, {})
(array([0.6       , 0.04025791]), -1.0, True, {})
(array([0.6       , 0.04082592]), -1.0, True, {})
(array([0.6       , 0.04239392]), -1.0, True, {})
(array([0.6       , 0.04396193]), -1.0, True, {})
(array([0.6       , 0.04552993]), -1.0, True, {})
(array([0.6       , 0.04709794]), -1.0, True, {})
(array([0.6       , 0.04866594]), -1.0, True, {})
(array([0.6       , 0.05023395]), -1.0, True, {})
(array([0.6       , 0.05180195]), -1.0, True, {})
(array([0.6       , 0.05336996]), -1.0, True, {})
(a